### ISSUE TITLE
Pull Request Lab: Part 1

### ISSUE THREAD

**Issue by carrieeyu** [hunter-classes/spring-2023-13500-lab-08-kellylau1#2]
A couple of suggestions I have:
(1) Change the cpp and h file name. It's currently labeled as "invert", which is a bit misleading as it doesn't pertain to all functions within those files.
(2) Add comments or a small description of what each function in the cpp file does. It would be helpful to have the specifics of what the intended output is supposed to be.

But overall, your code is great. The lines were spaced out and your program was neatly written.

- Carrie Yu

**Comment by kellylau1** [comment]
Okay thanks
